### ISSUE TITLE
Resource temporarily unavailable while fetching Data

### ISSUE THREAD

**Issue by kduchrow** [wubbl0rz/FiatChamp#1]
I got this Output while Starting the Addon: 

```
s6-rc: info: service legacy-services successfully started
FETCH DATA... 09/14/2022 19:17:00
Flurl.Http.FlurlHttpException: Call failed. Resource temporarily unavailable (loginmyuconnect.fiat.com:443): GET https://loginmyuconnect.fiat.com/accounts.webSdkBootstrap?apiKey=XXXXXX
 ---> System.Net.Http.HttpRequestException: Resource temporarily unavailable (loginmyuconnect.fiat.com:443)
 ---> System.Net.Sockets.SocketException (11): Resource temporarily unavailable
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|281_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   --- End of inner exception stack trace ---
   at Flurl.Http.FlurlRequest.HandleExceptionAsync(FlurlCall call, Exception ex, CancellationToken token)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Flurl.Http.ResponseExtensions.ReceiveJson[T](Task`1 response)
   at FiatClient.Login() in /FiatClient/FiatClient.cs:line 33
   at Program.<>c.<<<Main>$>b__0_0>d.MoveNext() in /FiatClient/Program.cs:line 54
```

Maybe you should expect this to happen. I'm not sure why this is happening, but maybe someone will experience the same issue. The following data fetch seems to work. Maybe it is only the first one after starting the Addon

**Comment by wubbl0rz** [comment]
so after that everything works ? i get this error too from time to time when the fiat site is not responding. it does look like the they don't have the best uptime 😁 maybe it looks like the addon crashed but its still running and will retry automatically in 15min. 

maybe i could implement some retry logic if the fiat site is temporary unavailable to retry right now or give better error message.

**Comment by wubbl0rz** [comment]
added a better error message in https://github.com/wubbl0rz/FiatChamp/commit/892dccbcb9a5e9d5252b7086f622930766e85b89 and pushed a new addon version.

i will have a look at faster retries in case when the fiat site is unavailable.

**Comment by kduchrow** [comment]
Thank you for the quick fix :)
