### ISSUE TITLE
(external) Mqtt without username and password is no longer working with latest release

### ISSUE THREAD

**Issue by McTristan** [wubbl0rz/FiatChamp#14]
All I get is:

```
[21:50:23] ERROR: Got unexpected response from the API: Service not enabled
Unhandled exception. Microsoft.Extensions.Options.OptionsValidationException: DataAnnotation validation failed for 'AppConfig' members: 'MqttUser' with the error: 'The MqttUser field is required.'.; DataAnnotation validation failed for 'AppConfig' members: 'MqttPw' with the error: 'The MqttPw field is required.'.
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.OptionsMonitor`1.<>c__DisplayClass10_0.<Get>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Microsoft.Extensions.Options.OptionsCache`1.GetOrAdd(String name, Func`1 createOptions)
   at Microsoft.Extensions.Options.OptionsMonitor`1.Get(String name)
   at Microsoft.Extensions.DependencyInjection.OptionsBuilderExtensions.<>c__DisplayClass0_1`1.<ValidateOnStart>b__1()
   at Microsoft.Extensions.DependencyInjection.ValidationHostedService.StartAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at Microsoft.Extensions.DependencyInjection.ValidationHostedService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Program.<Main>$(String[] args) in /home/runner/work/FiatChamp/FiatChamp/FiatChampAddon/FiatClient/Program.cs:line 39
   at Program.<Main>(String[] args)
/run.sh: line 29:   167 Aborted                 (core dumped) ./FiatChamp
```

It was working fine in the release before the latest version. Now it seems at least the user name is obligatory which does not work in my case (not using username and password).

**Comment by wubbl0rz** [comment]
im wondering why this worked before 😁 the mqtt username was always required for startup. i will make mqtt user and pw optional when using external broker.

**Comment by wubbl0rz** [comment]
could it be that the last time you started my addon you still had the mqtt addon running ? do your mqtt broker allow connecting with username / password even they are not needed ? 

but anyway i will remove required username/password if using external broker.

**Comment by wubbl0rz** [comment]
@McTristan made a fast fix and user/pw optional für mqtt. i hope this fixes the problem and don't break other stuff. not much time today :smile:

**Comment by McTristan** [comment]
Works again ... yeah! Thank you! Don't know why it worked before but now it is working again ;)
