### ISSUE TITLE
Post commands failing with 403

### ISSUE THREAD

**Issue by mrwhite31** [wubbl0rz/FiatChamp#49]
Hi. Are the POST commands still working for you? All POST commands are failing for me with 403. PIN is correct though. I turned on dangerous commands in config as well.

e.g. Blink command
[21:05:58 INF] SEND COMMAND HBLF: 
[21:05:58 DBG] {
  "Expiry": 600000,
  "Token": "...."
}
[21:05:59 ERR] Command: HBLF ERROR. Maybe wrong pin?
[21:05:59 DBG] Flurl.Http.FlurlHttpException: Call failed with status code 403 (Forbidden): POST https://channels.sdpr-01.fcagcv.com/v1/accounts/..../vehicles/..../remote
   at Flurl.Http.FlurlRequest.HandleExceptionAsync(FlurlCall call, Exception ex, CancellationToken token)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Flurl.Http.ResponseExtensions.ReceiveJson[T](Task`1 response)
   at FiatChamp.FiatClient.SendCommand(String vin, String command, String pin, String action) in /home/runner/work/FiatChamp/FiatChamp/FiatChampAddon/FiatClient/FiatClient.cs:line 556
   at Program.<>c__DisplayClass0_0.<<<Main>$>g__TrySendCommand|1>d.MoveNext() in /home/runner/work/FiatChamp/FiatChamp/FiatChampAddon/FiatClient/Program.cs:line 264

Thanks

**Comment by 00o-sh** [comment]
Same issue here not sure what it is yet I suspect this is a RAM/Mopar issue  have tried running a packet capture but I have an iphone and the requests in the app fail if https MITM is on so I cant see the auth packets to see if anything changed

[16:51:07 ERR] Command: RDL ERROR. Maybe wrong pin?
[16:51:07 DBG] Flurl.Http.FlurlHttpException: Call failed with status code 403 (Forbidden): POST https://mfa.fcl-01.fcagcv.com/v1/accounts/cd6748243a9a4997b98dce00179a33ac/ignite/pin/authenticate
   at Flurl.Http.FlurlRequest.HandleExceptionAsync(FlurlCall call, Exception ex, CancellationToken token)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Flurl.Http.ResponseExtensions.ReceiveJson[T](Task`1 response)
   at FiatChamp.FiatClient.SendCommand(String vin, String command, String pin, String action) in /home/runner/work/FiatChamp/FiatChamp/FiatChampAddon/FiatClient/FiatClient.cs:line 541
   at Program.<>c__DisplayClass0_0.<<<Main>$>g__TrySendCommand|1>d.MoveNext() in /home/runner/work/FiatChamp/FiatChamp/FiatChampAddon/FiatClient/Program.cs:line 264

**Comment by 00o-sh** [comment]
> Same issue here not sure what it is yet I suspect this is a RAM/Mopar issue have tried running a packet capture but I have an iphone and the requests in the app fail if https MITM is on so I cant see the auth packets to see if anything changed
> 
> [16:51:07 ERR] Command: RDL ERROR. Maybe wrong pin? [16:51:07 DBG] Flurl.Http.FlurlHttpException: Call failed with status code 403 (Forbidden): POST https://mfa.fcl-01.fcagcv.com/v1/accounts/cd6748243a9a4997b98dce00179a33ac/ignite/pin/authenticate at Flurl.Http.FlurlRequest.HandleExceptionAsync(FlurlCall call, Exception ex, CancellationToken token) at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption) at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption) at Flurl.Http.ResponseExtensions.ReceiveJson[T](Task`1 response) at FiatChamp.FiatClient.SendCommand(String vin, String command, String pin, String action) in /home/runner/work/FiatChamp/FiatChamp/FiatChampAddon/FiatClient/FiatClient.cs:line 541 at Program.<>c__DisplayClass0_0.<<
> 
> $>g__TrySendCommand|1>d.MoveNext() in /home/runner/work/FiatChamp/FiatChamp/FiatChampAddon/FiatClient/Program.cs:line 264

Did a PR fixing the PIN endpoint I am not sure how to test but my packet capture shows that being used

https://github.com/wubbl0rz/FiatChamp/pull/64

**Comment by jaroslaw-dutka** [comment]
I was facing same issue. After hours of fighting with an android emulator I was able to decrypt trafic and find out that problem lies in a commad "HBLF". Actual command for my Fiat 500e is "ROLIGHTS". I started testing with lights blink and didn't check other commands and assumed all of them are not working :).
