### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by KJThaDon** [wubbl0rz/FiatChamp#61]
Pin is correct and everything else seems to be functioning atm, but door lock/unlocks not working. Any ideas?

```
[05:13:43 ERR] Command: RDL ERROR. Maybe wrong pin?
[05:13:43 DBG] Flurl.Http.FlurlHttpException: Call failed with status code 403 (Forbidden): POST https://mfa.fcl-01.fcagcv.com/v1/accounts/**XXXXXXXXXX**/ignite/pin/authenticate
   at Flurl.Http.FlurlRequest.HandleExceptionAsync(FlurlCall call, Exception ex, CancellationToken token)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Flurl.Http.ResponseExtensions.ReceiveJson[T](Task`1 response)
   at FiatChamp.FiatClient.SendCommand(String vin, String command, String pin, String action) in /home/runner/work/FiatChamp/FiatChamp/FiatChampAddon/FiatClient/FiatClient.cs:line 541
   at Program.<>c__DisplayClass0_0.<<<Main>$>g__TrySendCommand|1>d.MoveNext() in /home/runner/work/FiatChamp/FiatChamp/FiatChampAddon/FiatClient/Program.cs:line 264
```

**Comment by KJThaDon** [comment]
ok so it seems those errors went away on there own, but the lock/unlock functions have not worked at all

This is with a RAM. Any ideas?

```
[07:04:50 INF] SEND COMMAND RDU: 
[07:04:50 INF] REFRESH SESSION
[07:04:50 ERR] Command: RDU ERROR. Maybe wrong pin?
[07:05:06 INF] SEND COMMAND RDL: 
[07:05:06 ERR] Command: RDL ERROR. Maybe wrong pin?
```

**Comment by AndyBowden** [comment]
I got the wrong pin message quite often in the past.
I deduce I made too many API calls and my Fiat UConnect account was locked out for 24 hours or so.
Suggest you try to log on to your Fiat Connect account from a browser. You might need to change the password. Then FiatChamp might start working again.

**Comment by KJThaDon** [comment]
> I got the wrong pin message quite often in the past. I deduce I made too many API calls and my Fiat UConnect account was locked out for 24 hours or so. Suggest you try to log on to your Fiat Connect account from a browser. You might need to change the password. Then FiatChamp might start working again.

Thanks, I'll try that. I do however have other information pulling. Maybe the unlock/locking uses a different route

**Comment by KJThaDon** [comment]
Didn't work. Still having same error
