### ISSUE TITLE
Alfa Romeo invalid login website

### ISSUE THREAD

**Issue by withay** [wubbl0rz/FiatChamp#85]
I'm getting the following error in my logs after successful communication w/MQTT:

```
[10:43:27 DBG] {
  "UID": null,
  "SessionInfo": null,
  "CallId": "7d05fd46db2642efa18812c8f771f40a",
  "ErrorCode": 403042,
  "ErrorDetails": "invalid loginID or password",
  "ErrorMessage": "Invalid LoginID",
  "ApiVersion": 2,
  "StatusCode": 403,
  "StatusReason": "Forbidden",
  "Time": "2024-11-16T15:43:27.748+00:00"
}
[10:43:27 ERR] System.Exception: Authentication failed. 403042 Forbidden Invalid LoginID
   at FiatResponse.ThrowOnError(String message) in /home/runner/work/FiatChamp/FiatChamp/FiatChampAddon/FiatClient/FiatResponse.cs:line 31
   at FiatChamp.FiatClient.Login() in /home/runner/work/FiatChamp/FiatChamp/FiatChampAddon/FiatClient/FiatClient.cs:line 448
   at FiatChamp.FiatClient.LoginAndKeepSessionAlive() in /home/runner/work/FiatChamp/FiatChamp/FiatChampAddon/FiatClient/FiatClient.cs:line 396
   at Program.<>c__DisplayClass0_0.<<<Main>$>b__0>d.MoveNext() in /home/runner/work/FiatChamp/FiatChamp/FiatChampAddon/FiatClient/Program.cs:line 72
[10:43:27 INF] Fetching COMPLETED. Next update in 15 minutes.
```

I AM able to log into Alfa Connect's website, though, and doublechecked my login info.

I believe the actual website that FiatChamp is using is incorrect. It uses **_https://myalfaconnect.alfaromeo.com/_** and I THINK it SHOULD be using: **_https://connect.alfaromeo.com/us/en/login_**

Can this be changed - or is this something I could figure out how to go in and change?

**Comment by Blueion76** [comment]
@withay I believe I have this working in my fork, If you don't mind testing: https://github.com/Blueion76/FCAUconnect-HA

**Comment by withay** [comment]
> @withay I believe I have this working in my fork, If you don't mind testing: https://github.com/Blueion76/FCAUconnect-HA

Heh well look at YOU fixing things! Yep, it worked, thank you! That's a LOT of information and sensors!

 Bonus question! I have a Dodge Ram - how do I add a SECOND vehicle???

**Comment by Blueion76** [comment]
> > @withay I believe I have this working in my fork, If you don't mind testing: https://github.com/Blueion76/FCAUconnect-HA
> 
> Heh well look at YOU fixing things! Yep, it worked, thank you! That's a LOT of information and sensors!
> 
> Bonus question! I have a Dodge Ram - how do I add a SECOND vehicle???

Easiest way for now is probably to fork the repository and add it as a second addon. I honestly have no clue where to begin with adding multiple brands support - sorry I couldn't be of more help.

**Comment by withay** [comment]
> > > @withay I believe I have this working in my fork, If you don't mind testing: https://github.com/Blueion76/FCAUconnect-HA
> > 
> > 
> > Heh well look at YOU fixing things! Yep, it worked, thank you! That's a LOT of information and sensors!
> > Bonus question! I have a Dodge Ram - how do I add a SECOND vehicle???
> 
> Easiest way for now is probably to fork the repository and add it as a second addon. I honestly have no clue where to begin with adding multiple brands support - sorry I couldn't be of more help.

Heh no way - you got it working for me - I definitely appreciate it!
